# Generated by Django 5.2.4 on 2025-09-06 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id_station",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=30)),
                ("line", models.CharField(max_length=1)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("metro", "Metro"),
                            ("cable", "Cable"),
                            ("bus", "Bus"),
                            ("tranvia", "Tranvia"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "perfil",
                    models.CharField(
                        choices=[
                            ("Frecuente", "Frecuente"),
                            ("AdultoMayor", "Adulto Mayor"),
                            ("Estudiantil", "Estudiantil"),
                            ("PcD", "PcD"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "lenguaje",
                    models.CharField(
                        blank=True,
                        choices=[("Español", "Español"), ("Ingles", "Inglés")],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_package", models.IntegerField()),
                (
                    "perfil",
                    models.CharField(
                        choices=[
                            ("Frecuente", "Frecuente"),
                            ("AdultoMayor", "Adulto Mayor"),
                            ("Estudiantil", "Estudiantil"),
                            ("PcD", "PcD"),
                            ("Eventual", "Eventual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.FloatField()),
            ],
            options={
                "unique_together": {("id_package", "perfil")},
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                ("id_route", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.FloatField()),
                (
                    "criterion",
                    models.CharField(
                        choices=[("precio", "Precio"), ("tiempo", "Tiempo")],
                        max_length=20,
                    ),
                ),
                (
                    "id_end",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="end_routes",
                        to="metroversoApp.station",
                    ),
                ),
                (
                    "id_start",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_routes",
                        to="metroversoApp.station",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metroversoApp.user",
                    ),
                ),
            ],
        ),
    ]
