# Generated by Django 5.2.4 on 2025-10-02 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                ("id_route", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.FloatField()),
                (
                    "criterion",
                    models.CharField(
                        choices=[("precio", "Precio"), ("tiempo", "Tiempo")],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id_station",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=30)),
                ("line", models.CharField(max_length=1)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("metro", "Metro"),
                            ("cable", "Cable"),
                            ("bus", "Bus"),
                            ("tranvia", "Tranvia"),
                            ("metroplus", "Metroplus"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_package", models.IntegerField()),
                (
                    "perfil",
                    models.CharField(
                        choices=[
                            ("Frecuente", "Frecuente"),
                            ("AdultoMayor", "Adulto Mayor"),
                            ("Estudiantil", "Estudiantil"),
                            ("PcD", "PcD"),
                            ("Eventual", "Eventual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.FloatField()),
            ],
            options={
                "unique_together": {("id_package", "perfil")},
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("route", "Shared Route"),
                            ("comment", "General Comment"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metroversoApp.route",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="route",
            name="id_end",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="end_routes",
                to="metroversoApp.station",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="id_start",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="start_routes",
                to="metroversoApp.station",
            ),
        ),
        migrations.CreateModel(
            name="PointOfInterest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant"),
                            ("shop", "Shop"),
                            ("bank", "Bank"),
                            ("pharmacy", "Pharmacy"),
                            ("hospital", "Hospital"),
                            ("hotel", "Hotel"),
                            ("gas_station", "Gas Station"),
                            ("entertainment", "Entertainment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200)),
                ("distance_from_station", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_of_interest",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nearby_points",
                        to="metroversoApp.station",
                    ),
                ),
            ],
            options={
                "ordering": ["station", "name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "perfil",
                    models.CharField(
                        choices=[
                            ("Frecuente", "Frecuente"),
                            ("AdultoMayor", "Adulto Mayor"),
                            ("Estudiantil", "Estudiantil"),
                            ("PcD", "PcD"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "lenguaje",
                    models.CharField(
                        blank=True,
                        choices=[("Español", "Español"), ("Ingles", "Inglés")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "django_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metro_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="route",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="metroversoApp.user"
            ),
        ),
        migrations.CreateModel(
            name="StationService",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("restroom", "Restrooms"),
                            ("wifi", "WiFi"),
                            ("atm", "ATM"),
                            ("ticket_office", "Ticket Office"),
                            ("accessibility", "Accessibility Features"),
                            ("commercial", "Commercial Area"),
                            ("parking", "Parking"),
                            ("security", "Security"),
                            ("elevator", "Elevator"),
                            ("escalator", "Escalator"),
                            ("phone", "Public Phone"),
                            ("lost_found", "Lost & Found"),
                            ("information", "Information Desk"),
                            ("first_aid", "First Aid"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Under Maintenance"),
                            ("coming_soon", "Coming Soon"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "hours",
                    models.CharField(blank=True, default="6:00-23:00", max_length=100),
                ),
                ("floor", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="metroversoApp.station",
                    ),
                ),
            ],
            options={
                "ordering": ["station", "service_type"],
                "unique_together": {("station", "service_type")},
            },
        ),
    ]
