# Generated by Django 5.2.4 on 2025-09-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metroversoApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="type",
            field=models.CharField(
                choices=[
                    ("metro", "Metro"),
                    ("cable", "Cable"),
                    ("bus", "Bus"),
                    ("tranvia", "Tranvia"),
                    ("metroplus", "Metroplus"),
                ],
                max_length=20,
            ),
        ),
    ]
