# Generated by Django 5.2.4 on 2025-10-12 03:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroversoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
