# Generated by Django 5.2.4 on 2025-10-13 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metroversoApp', '0002_route_end_time_route_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_time',
        ),
    ]
