# Generated by Django 5.2.4 on 2025-10-13 00:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroversoApp', '0003_remove_route_end_time_remove_route_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
