# Generated by Django 5.2.4 on 2025-10-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroversoApp', '0004_route_end_time_route_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.CharField(choices=[('Frecuente', 'Frecuente'), ('AdultoMayor', 'Adulto Mayor'), ('Estudiantil', 'Estudiantil'), ('PcD', 'PcD'), ('Eventual', 'Al portador y eventual')], max_length=20),
        ),
    ]
