# Generated by Django 5.2.4 on 2025-10-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroversoApp', '0005_alter_user_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='selected_profile',
            field=models.CharField(blank=True, choices=[('Frecuente', 'Frecuente'), ('AdultoMayor', 'Adulto Mayor'), ('Estudiantil', 'Estudiantil'), ('PcD', 'PcD'), ('Eventual', 'Al portador y eventual')], max_length=20, null=True),
        ),
    ]
