# Generated by Django 5.2.4 on 2025-10-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metroversoApp', '0006_route_selected_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='selected_profile',
        ),
    ]
