# Generated by Django 5.2.4 on 2025-10-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroversoApp', '0007_remove_route_selected_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='criterion',
            field=models.CharField(choices=[('tiempo', 'Tiempo'), ('distancia', 'Distancia'), ('transferencias', 'Transferencias')], max_length=20),
        ),
    ]
