# Generated by Django 5.2.4 on 2025-10-16 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metroversoApp', '0008_alter_route_criterion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='perfil',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('id_package', 'profile')},
        ),
    ]
